sweettooth/review/urls.py
from django.conf.urls import patterns, url
from django.views.generic.list import ListView

from sweettooth.extensions.models import ExtensionVersion
from sweettooth.review import views

urlpatterns = patterns('',
    url(r'^$', ListView.as_view(template_name='review/list.html',
                                queryset=ExtensionVersion.objects.unreviewed(),
                                context_object_name='version_list'),
        name='review-list'),
    url(r'^ajax/get-file/(?P<pk>\d+)', views.ajax_get_file_view, name='review-ajax-files'),
    url(r'^ajax/get-file-list/(?P<pk>\d+)', views.ajax_get_file_list_view, name='review-ajax-file-list'),
    url(r'^ajax/get-file-diff/(?P<pk>\d+)', views.ajax_get_file_diff_view, name='review-ajax-file-diff'),
    url(r'^submit/(?P<pk>\d+)', views.submit_review_view, name='review-submit'),

    url(r'^download/(?P<pk>\d+)\.shell-extension.zip$',
        views.download_zipfile, name='review-download'),

    url(r'^(?P<pk>\d+)', views.review_version_view, name='review-version'),

)

sweettooth/urls.py
import os.path

from django.conf.urls import patterns, include, url, handler404, handler500
from django.conf import settings
from django.http import HttpResponse

from django.contrib import admin
from django.views import static
from django.views.generic.base import TemplateView
admin.autodiscover()

urlpatterns = patterns('',
    # 'login' and 'register'
    url(r'^accounts/', include('sweettooth.auth.urls')),
    url(r'^', include('sweettooth.extensions.urls'), name='index'),

    url(r'^review/', include('sweettooth.review.urls')),
    url(r'^errors/', include('sweettooth.errorreports.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/', include('sweettooth.ratings.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
)

if settings.DEBUG:
    # Use static.serve for development...
    urlpatterns.append(url(r'^extension-data/(?P<path>.*)', static.serve,
                           dict(document_root=settings.MEDIA_ROOT), name='extension-data'))
else:
    # and a dummy to reverse on for production.
    urlpatterns.append(url(r'^extension-data/(?P<path>.*)', lambda *a, **kw: HttpResponse(),
                           name='extension-data'))

sweettooth/extensions/models.py
import json

from zipfile import ZipFile, BadZipfile

from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db import models
from django.dispatch import Signal

import autoslug
import re

(STATUS_UNREVIEWED,
 STATUS_REJECTED,
 STATUS_INACTIVE,
 STATUS_ACTIVE,
 STATUS_WAITING) = xrange(5)

STATUSES = {
    STATUS_UNREVIEWED: u"Unreviewed",
    STATUS_REJECTED: u"Rejected",
    STATUS_INACTIVE: u"Inactive",
    STATUS_ACTIVE: u"Active",
    STATUS_WAITING: u"Waiting for author",
}

def validate_uuid(uuid):
    if re.match(r'[-a-zA-Z0-9@._]+$', uuid) is None:
        return False

    # Don't blacklist "gnome.org" - we don't want to eliminate
    # world-of-gnome.org or something like that.
    if re.search(r'[.@]gnome\.org$', uuid) is not None:
        return False

    return True

class ExtensionManager(models.Manager):
    def visible(self):
        return self.filter(versions__status=STATUS_ACTIVE).distinct()

    def create_from_metadata(self, metadata, **kwargs):
        instance = self.model(**kwargs)
        instance.parse_metadata_json(metadata)
        instance.save()
        return instance

def build_shell_version_map(versions):
    shell_version_map = {}
    for version in versions:
        for shell_version in version.shell_versions.all():
            key = shell_version.version_string
            if key not in shell_version_map:
                shell_version_map[key] = version

            if version.version > shell_version_map[key].version:
                shell_version_map[key] = version

    for key, version in shell_version_map.iteritems():
        shell_version_map[key] = dict(pk = version.pk,
                                      version = version.version)

    return shell_version_map

def build_shell_version_array(versions):
    shell_version_map = {}

    for version in versions:
        for shell_version in version.shell_versions.all():
            key = shell_version.version_string
            if key not in shell_version_map:
                shell_version_map[key] = {}

            if version.pk not in shell_version_map[key]:
                shell_version_map[key][version.pk] = dict(
                    pk=version.pk,
                    version=version.version)

    return shell_version_map


def make_screenshot_filename(obj, filename=None):
    return "screenshots/screenshot_%d.png" % (obj.pk,)


def make_icon_filename(obj, filename=None):
    return "icons/icon_%d.png" % (obj.pk,)


class Extension(models.Model):
    name = models.CharField(max_length=200)
    uuid = models.CharField(max_length=200, unique=True, db_index=True)
    slug = autoslug.AutoSlugField(populate_from="name")
    creator = models.ForeignKey(User, db_index=True)
    description = models.TextField(blank=True)
    url = models.URLField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    downloads = models.PositiveIntegerField(default=0)
    popularity = models.IntegerField(default=0)

    class Meta:
        permissions = (
            ("can-modify-data", "Can modify extension data"),
        )

    screenshot = models.ImageField(upload_to=make_screenshot_filename, blank=True)
    icon = models.ImageField(upload_to=make_icon_filename, blank=True, default="/static/images/plugin.png")

    objects = ExtensionManager()

    def __unicode__(self):
        return self.uuid

    def parse_metadata_json(self, metadata):
        self.name = metadata.pop('name', "")
        self.description = metadata.pop('description', "")
        self.url = metadata.pop('url', "")
        self.uuid = metadata['uuid']

    def clean(self):
        from django.core.exceptions import ValidationError

        if not validate_uuid(self.uuid):
            raise ValidationError("Your extension has an invalid UUID")

    def save(self, replace_metadata_json=True, *args, **kwargs):
        super(Extension, self).save(*args, **kwargs)
        if replace_metadata_json:
            for version in self.versions.all():
                if version.source:
                    try:
                        version.replace_metadata_json()
                    except BadZipfile, e:
                        # Ignore bad zipfiles, we don't care
                        pass

    def get_absolute_url(self):
        return reverse('extensions-detail', kwargs=dict(pk=self.pk,
                                                        slug=self.slug))

    def user_can_edit(self, user):
        if user == self.creator:
            return True
        if user.has_perm('extensions.can-modify-data'):
            return True
        return False

    @property
    def first_line_of_description(self):
        if not self.description:
            return ""
        return self.description.splitlines()[0]

    @property
    def visible_versions(self):
        return self.versions.filter(status=STATUS_ACTIVE)

    @property
    def latest_version(self):
        try:
            return self.visible_versions.latest()
        except ExtensionVersion.DoesNotExist:
            return None

    @property
    def visible_shell_version_map(self):
        return build_shell_version_map(self.visible_versions)

    @property
    def visible_shell_version_array(self):
        return build_shell_version_array(self.visible_versions)

class ExtensionPopularityItem(models.Model):
    extension = models.ForeignKey(Extension, db_index=True,
                                  related_name='popularity_items')
    offset = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)

class InvalidShellVersion(Exception):
    pass


def parse_version_string(version_string):
    version = version_string.split('.')

    try:
        major, minor = version[:2]
        major, minor = int(major), int(minor)
    except ValueError, e:
        raise InvalidShellVersion()

    if len(version) in (3, 4):
        # 3.0.1, 3.1.4
        try:
            point = int(version[2])
        except ValueError, e:
            raise InvalidShellVersion()

    elif len(version) == 2 and minor % 2 == 0:
        # 3.0, 3.2
        point = -1
    else:
        # Two-digit odd versions are illegal: 3.1, 3.3
        raise InvalidShellVersion()

    return major, minor, point

class ShellVersionManager(models.Manager):
    def lookup_for_version_string(self, version_string):
        major, minor, point = parse_version_string(version_string)
        try:
            return self.get(major=major, minor=minor, point=point)
        except self.model.DoesNotExist:
            return None

    def get_for_version_string(self, version_string):
        major, minor, point = parse_version_string(version_string)
        try:
            obj = self.get(major=major, minor=minor, point=point)
        except self.model.DoesNotExist:
            obj = self.create(major=major, minor=minor, point=point)

        return obj

class ShellVersion(models.Model):
    major = models.PositiveIntegerField()
    minor = models.PositiveIntegerField()

    # -1 is a flag for the stable release matching
    point = models.IntegerField()

    objects = ShellVersionManager()

    def __unicode__(self):
        return self.version_string

    @property
    def version_string(self):
        if self.point == -1:
            return "%d.%d" % (self.major, self.minor)

        return "%d.%d.%d" % (self.major, self.minor, self.point)

class InvalidExtensionData(Exception):
    pass


def parse_zipfile_metadata(uploaded_file):
    """
    Given a file, extract out the metadata.json, parse, and return it.
    """
    try:
        zipfile = ZipFile(uploaded_file, 'r')
    except BadZipfile:
        raise InvalidExtensionData("Invalid zip file")

    if zipfile.testzip() is not None:
        raise InvalidExtensionData("Invalid zip file")

    total_uncompressed = sum(i.file_size for i in zipfile.infolist())
    if total_uncompressed > 5*1024*1024: # 5 MB
        raise InvalidExtensionData("Zip file is too large")

    try:
        metadata = json.load(zipfile.open('metadata.json', 'r'))
    except KeyError:
        # no metadata.json in archive, raise error
        raise InvalidExtensionData("Missing metadata.json")
    except ValueError:
        # invalid JSON file, raise error
        raise InvalidExtensionData("Invalid JSON data")

    zipfile.close()
    return metadata

# uuid max length + suffix max length
filename_max_length = Extension._meta.get_field('uuid').max_length + len(".v000.shell-version.zip")

class ExtensionVersionManager(models.Manager):
    def unreviewed(self):
        return self.filter(status=STATUS_UNREVIEWED)

    def waiting(self):
        return self.filter(status=STATUS_WAITING)

    def visible(self):
        return self.filter(status=STATUS_ACTIVE)


def make_filename(obj, filename=None):
    return "%s.v%d.shell-extension.zip" % (obj.extension.uuid, obj.version)


class ExtensionVersion(models.Model):
    extension = models.ForeignKey(Extension, related_name="versions")
    version = models.IntegerField(default=0)
    extra_json_fields = models.TextField()
    status = models.PositiveIntegerField(choices=STATUSES.items())
    shell_versions = models.ManyToManyField(ShellVersion)

    class Meta:
        unique_together = ('extension', 'version'),
        get_latest_by = 'version'

    def __unicode__(self):
        return "Version %d of %s" % (self.version, self.extension)

    source = models.FileField(upload_to=make_filename,
                              max_length=filename_max_length)

    objects = ExtensionVersionManager()

    @property
    def shell_versions_json(self):
        return json.dumps([sv.version_string for sv in self.shell_versions.all()])

    def make_metadata_json(self):
        """
        Return generated contents of metadata.json
        """
        data = json.loads(self.extra_json_fields)
        fields = dict(
            _generated  = "Generated by SweetTooth, do not edit",
            name        = self.extension.name,

sweettooth/review/models.py
from django.contrib.auth.models import User, Permission, Group
from django.db import models
from django.db.models import Q

from sweettooth.extensions.models import ExtensionVersion, STATUSES

def get_all_reviewers():
    perm = Permission.objects.get(codename="can-review-extensions")

    # Dark magic to get all the users with a specific permission
    # Thanks to <schinckel> in #django
    groups = Group.objects.filter(permissions=perm)
    return User.objects.filter(Q(is_superuser=True)|Q(user_permissions=perm)|Q(groups__in=groups)).distinct()

class CodeReview(models.Model):
    reviewer = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)
    comments = models.TextField(blank=True)
    version = models.ForeignKey(ExtensionVersion, related_name="reviews")
    new_status = models.PositiveIntegerField(choices=STATUSES.items(), null=True)
    auto = models.BooleanField(default=False)

    class Meta:
        permissions = (
            ("can-review-extensions", "Can review extensions"),
            ("trusted", "Trusted author"),
        )

sweettooth/review/templates/review/list.html
{% extends "base.html" %}

{% block title %}Unreviewed Extensions - {{ block.super }}{% endblock %}

{% block body %}
<h2>Unreviewed Extensions</h2>
<ul class="extensions">
{% for version in version_list %}
{% with version.extension as extension %}
<li class="extension">
  <h3 class="extension-name"><a href="{% url 'review-version' pk=version.pk %}"><img src="{{ extension.icon.url }}" class="icon">{{ extension.name }}</a></h3>
  <span class="version">(v{{ version.version }})</span>
  <span class="author">by <a href="{% url 'auth-profile' user=extension.creator %}">{{ extension.creator }}</a></span>
  <p class="description">{{ extension.first_line_of_description }}</p>
</li>
{% endwith %}
{% endfor %}
</ul>
{% endblock %}

sweettooth/review/templates/review/review.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %}Review "{{ extension.name }}" - {{ block.super }}{% endblock %}

{% block body %}
<h2 class="expandy_header expanded col-xs-12 col-sm-12 col-md-12 col-lg-12">Details Page Preview</h2>
<div id="preview">
  <div class="extension single-page">
    <div class="extension-header col-xs-12 col-sm-12 col-md-12 col-lg-12">
        {% spaceless %}
            <h3 class="extension-name">
                <a href="{{ extension.get_absolute_url }}">
                    <img src="{{ extension.icon.url }}" class="icon">{{ extension.name }}
                </a>
            </h3>

            <span class="author"> by <a
                    href="{% url 'auth-profile' user=extension.creator %}">{{ extension.creator }}</a></span>
        {% endspaceless %}
    </div>

    <div class="extension-details">
        {% if extension.screenshot %}
            <div class="screenshot col-xs-12 col-sm-5 col-md-4 col-lg-3">
                <a href="{{ extension.screenshot.url }}" class="screenshot"><img
                        src="{{ extension.screenshot.url }}"></a>
            </div>

            <div class="col-sm-1 col-md-1 col-lg-1">
            </div>
        {% endif %}

        <div class="col-xs-12 col-sm-6 col-md-7 col-lg-8">
            <p class="description">{{ extension.description }}</p>

            <dl>
                {% if extension.url %}
                    <dt>Extension Homepage</dt>
                    <dd><a href="{{ extension.url }}" id="extension_url">{{ extension.url }}</a></dd>
                {% endif %}
            </dl>
        </div>
    </div>

    <hr>

    No comments.
    <div class="clear"></div>
  </div>
</div>

{% if has_old_version %}
<h2 class="expandy_header expanded col-xs-12 col-sm-12 col-md-12 col-lg-12">Diff Against Previous Version</h2>
<div id="diff" data-pk="{{ version.pk }}" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
</div>
{% endif %}

<h2 class="expandy_header{% if not has_old_version %} expanded{% endif %} col-xs-12 col-sm-12 col-md-12 col-lg-12">Files</h2>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div id="files" data-pk="{{ version.pk }}">
  </div>
  <p>Note: Binary files aren't shown on the web site. To see all
    files, please <a href="{% url 'review-download' pk=version.pk %}">download
      the extension zipfile</a>.</p>
</div>

<h2 class="expandy_header expanded col-xs-12 col-sm-12 col-md-12 col-lg-12">All Versions</h2>
<div id="all_versions">
  <table>
    <thead>
      <th>Version</th>
      <th>Status</th>
    </thead>
    <tbody>
      {% comment %}
      This is somewhat confusing. 'ver' is the loop variable across
      all extension versions. 'version' is the current version.
      {% endcomment %}
      {% for ver in all_versions %}
      <tr>
        <td> {{ ver.version }} </td>
        <td>
          {% if ver.version == version.version %}
          <span class="current_version extension-status {{ ver.get_status_class }}">{{ ver.get_status_display }}</span>
          {% else %}
          <a class="extension-status {{ ver.get_status_class }}" href="{% url 'review-version' pk=ver.pk %}">{{ ver.get_status_display }}</a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% if previous_reviews %}
<h2 class="expandy_header expanded col-xs-12 col-sm-12 col-md-12 col-lg-12">Previous Reviews on this Version</h2>
<div id="previous_reviews" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  {% for review in previous_reviews %}
  <div class="review">
    <a class="review-author" href="{% url 'auth-profile' user=review.reviewer.username %}">{{ review.reviewer }}</a>
    {% if review.new_status %}
    <span class="extension-status {{ review.get_new_status_display|lower }}">
      {% if review.auto %}auto-{% endif%}
      {{ review.get_new_status_display|lower }}
    </span>
    {% else %}
    posted a review
    {% endif %}
    <time title="{{ review.date|date:"c" }}Z">{{ review.date|date:"F j, Y" }}</time>
    <blockquote>{{ review.comments }}</blockquote>
  </div>
  {% empty %}
  <p>No reviews.</p>
  {% endfor %}
</div>
{% endif %}

{% if can_review %}
<h2 class="expanded col-xs-12 col-sm-12 col-md-12 col-lg-12">Review</h2>

<div id="review" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <form id="review_form" action="{% url 'review-submit' pk=version.pk %}" method="POST">
    {% csrf_token %}
    <textarea id="comments" name="comments"></textarea>
    <select name="status">
      <option value="none" selected>No change</option>
{% if can_approve %}
      <option value="approve" class="approve">Approve</option>
{% endif %}
      <option value="reject" class="reject">Reject</option>
      <option value="wait" class="waiting">Needs reply from author</option>
    </select>
    <input type="submit" value="Submit">
  </form>
</div>
{% endif %}

{% endblock %}

{% block head %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'css/review.css' %}" />
  <script>
      jQuery(function ($) {
          require(['review-main'], function(){});
      });
  </script>
{% endblock %}